### ISSUE TITLE
Header structure in Paper vs Code

### ISSUE THREAD

**Issue by mustard123** [rpp0/gr-lora#106]
Thank you very much for answering my questions so far. I have another one regarding your paper.

Is my understanding correct that the header structure described in your paper and the one defined in code (loraphy.h) differs?

It seems to me that in code the order is:
length 1byte
crc high nibble 4 bits
mac crc presence flag 1 bit
coding rate 3 bits
crc low nibble 4 bits
reserved 4 bits

whereas in the paper the order you describe is:
length 1 byte
coding rate 3 bits
mac crc  presence 1 bit
crc high nibble 4 bits
crc low nibble 4 bits

Which one is correct?
Much appreciated

![lora_header_paper](https://user-images.githubusercontent.com/14769359/66334471-6ba69e00-e939-11e9-9959-0d7be3ad2eb0.png)
![lora_phy_header](https://user-images.githubusercontent.com/14769359/66334472-6ba69e00-e939-11e9-838d-bf0f58e28e81.png)
![lora-phy-header-figure](https://user-images.githubusercontent.com/14769359/66334992-68f87880-e93a-11e9-9a1f-d85e040d1a40.png)
why is this going from 7 to 0 and not in order i.e from 0 to 7?

**Comment by rpp0** [comment]
> Which one is correct?

Both are correct for bytes 0 and 1. They are just listed in different order in the code because of the way bit fields work in C. It does seem that in the code, "crc_lsn" and "reserved" should actually be swapped. If you want, you can make a pull request for this. Thanks for noticing!

> why is this going from 7 to 0 and not in order i.e from 0 to 7?

Bit 0 usually refers to the LSB of a field, whereas byte 0 of a packet is usually the leftmost byte. See: https://en.wikipedia.org/wiki/Bit_field
